#!/usr/bin/env python3
"""Run zero-network runtime/config compatibility canaries."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

import yaml


GENERATED_MARKER = "Generated by dev-template tools/template.py. Do not edit directly."
SAFE_INVOCATIONS = {
    "codex": {"version_args": ["--version"], "help_args": ["--help"]},
    "claude": {"version_args": ["--bare", "--version"], "help_args": ["--bare", "--help"]},
}


class CanaryError(ValueError):
    pass


def load_yaml(path: Path) -> dict:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, yaml.YAMLError) as error:
        raise CanaryError(f"cannot read {path}: {error}") from error
    if not isinstance(data, dict):
        raise CanaryError(f"{path} must contain a YAML mapping")
    return data


def load_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise CanaryError(f"cannot read {path}: {error}") from error
    if not isinstance(data, dict):
        raise CanaryError(f"{path} must contain a JSON object")
    return data


def exact_keys(data: dict, expected: set[str], label: str) -> None:
    if not isinstance(data, dict) or set(data) != expected:
        actual = set(data) if isinstance(data, dict) else set()
        raise CanaryError(
            f"{label} keys differ: "
            f"missing={sorted(expected - actual, key=str)}, "
            f"unused={sorted(actual - expected, key=str)}"
        )


def command_output(command: str, arguments: list[str]) -> str:
    try:
        result = subprocess.run(
            [command, *arguments],
            check=True,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, UnicodeError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        raise CanaryError(f"offline command failed: {command} {' '.join(arguments)}: {error}") from error
    return result.stdout.strip() or result.stderr.strip()


def validate_cli_contract(config: dict) -> dict[str, str]:
    exact_keys(
        config,
        {"version", "network_behavior", "model_availability", "runtimes"},
        "runtime compatibility contract",
    )
    if type(config["version"]) is not int or config["version"] != 1 or config["network_behavior"] != "forbidden":
        raise CanaryError("runtime canary must remain version 1 and zero-network")
    if config["model_availability"] != "not_checked_offline":
        raise CanaryError("runtime canary must not imply remote model availability was checked")
    if not isinstance(config["runtimes"], dict) or set(config["runtimes"]) != {"codex", "claude"}:
        raise CanaryError("runtime canary must bind Codex and Claude")
    versions: dict[str, str] = {}
    for runtime, spec in config["runtimes"].items():
        exact_keys(
            spec,
            {"command", "version_args", "help_args", "tested_version", "version_pattern", "help_markers"},
            f"{runtime} canary",
        )
        if not isinstance(spec["command"], str) or not spec["command"].strip():
            raise CanaryError(f"{runtime} canary command must be a non-empty string")
        for field in ("version_args", "help_args", "help_markers"):
            values = spec[field]
            if (
                not isinstance(values, list)
                or not values
                or not all(isinstance(value, str) and value.strip() for value in values)
                or len(values) != len(set(values))
            ):
                raise CanaryError(f"{runtime} canary {field} must contain unique non-empty strings")
        expected_invocation = SAFE_INVOCATIONS[runtime]
        if spec["command"] != runtime or any(
            spec[field] != expected_invocation[field] for field in ("version_args", "help_args")
        ):
            raise CanaryError(f"{runtime} canary may invoke only its local version and help commands")
        if not isinstance(spec["version_pattern"], str) or not spec["version_pattern"]:
            raise CanaryError(f"{runtime} canary version pattern must be a non-empty string")
        if not isinstance(spec["tested_version"], str) or not spec["tested_version"]:
            raise CanaryError(f"{runtime} tested version must be a non-empty string")
        try:
            version_pattern = re.compile(spec["version_pattern"])
        except re.error as error:
            raise CanaryError(f"{runtime} canary version pattern is invalid: {error}") from error
        if version_pattern.groups != 1:
            raise CanaryError(f"{runtime} canary version pattern must capture exactly one version")
        version_output = command_output(spec["command"], spec["version_args"])
        match = version_pattern.fullmatch(version_output)
        if match is None:
            raise CanaryError(f"{runtime} returned an unexpected version string: {version_output!r}")
        actual_version = match.group(1)
        if actual_version != spec["tested_version"]:
            raise CanaryError(
                f"{runtime} version {actual_version} differs from tested {spec['tested_version']}; review before updating the canary"
            )
        help_output = command_output(spec["command"], spec["help_args"])
        missing = [marker for marker in spec["help_markers"] if marker not in help_output]
        if missing:
            raise CanaryError(f"{runtime} help contract lost markers: {missing}")
        versions[runtime] = actual_version
    return versions


def parse_claude_frontmatter(path: Path) -> tuple[dict, str]:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise CanaryError(f"cannot read {path}: {error}") from error
    if not text.startswith("---\n") or "---\n" not in text[4:]:
        raise CanaryError(f"{path} has invalid YAML frontmatter")
    _, frontmatter, body = text.split("---\n", 2)
    try:
        metadata = yaml.safe_load(frontmatter)
    except yaml.YAMLError as error:
        raise CanaryError(f"cannot parse {path} frontmatter: {error}") from error
    if not isinstance(metadata, dict):
        raise CanaryError(f"{path} frontmatter must be a YAML mapping")
    return metadata, body


def generated_text(path: Path, label: str) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise CanaryError(f"cannot read {path}: {error}") from error
    if GENERATED_MARKER not in text:
        raise CanaryError(f"{label} is missing its generated ownership marker: {path}")
    return text


def validate_minimal_project(root: Path, repo: Path, *, allow_optional_roles: bool = False) -> None:
    try:
        guidance = (repo / "maintainer/guidance.md").read_text(encoding="utf-8").strip()
    except (OSError, UnicodeError) as error:
        raise CanaryError(f"cannot read maintainer guidance: {error}") from error
    if not guidance:
        raise CanaryError("maintainer guidance must not be empty")
    for filename in ("AGENTS.md", "CLAUDE.md"):
        text = generated_text(root / filename, filename)
        if guidance not in text:
            raise CanaryError(f"{filename} drifted from maintainer/guidance.md")
    if not (root / "AI.md").is_file():
        raise CanaryError(f"{root} is missing AI.md")

    forbidden = [
        ".codex/config.toml",
        ".ai/skills",
        ".agents/skills",
        ".claude/skills",
        ".codex/skills",
        ".ai/generators/compile.py",
    ]
    if not allow_optional_roles:
        forbidden.extend((".codex/agents", ".claude/agents"))
    present = [relative for relative in forbidden if (root / relative).exists()]
    if present:
        raise CanaryError(f"{root} default profile contains retired runtime assets: {present}")


def role_map(repo: Path) -> dict[str, dict]:
    source = load_yaml(repo / "optional/roles.yaml")
    exact_keys(source, {"version", "roles"}, "optional role source")
    if source["version"] != 1 or not isinstance(source["roles"], dict) or not source["roles"]:
        raise CanaryError("optional role source must be schema-v1 with roles")
    for name, role in source["roles"].items():
        if not isinstance(name, str) or not re.fullmatch(r"[a-z][a-z0-9-]*", name):
            raise CanaryError("optional role names must be kebab-case")
        exact_keys(role, {"description", "instructions", "access"}, f"optional role {name}")
        if not all(isinstance(role[field], str) and role[field].strip() for field in role):
            raise CanaryError(f"optional role {name} has an empty field")
    return source["roles"]


def runtime_bindings(repo: Path) -> dict:
    bindings = load_json(repo / "optional/runtime-bindings.json")
    exact_keys(bindings, {"codex", "claude"}, "optional runtime bindings")
    return bindings


def validate_optional_roles(root: Path, repo: Path) -> None:
    roles = role_map(repo)
    bindings = runtime_bindings(repo)
    codex_bindings = bindings["codex"]
    claude_bindings = bindings["claude"]
    if not isinstance(codex_bindings, dict) or not isinstance(claude_bindings, dict):
        raise CanaryError("optional runtime bindings must contain objects")

    expected_codex = {f"{name}.toml" for name in roles}
    expected_claude = {f"{name}.md" for name in roles}
    actual_codex = {path.name for path in (root / ".codex/agents").glob("*.toml")}
    actual_claude = {path.name for path in (root / ".claude/agents").glob("*.md")}
    if actual_codex != expected_codex or actual_claude != expected_claude:
        raise CanaryError(
            f"{root} optional role files differ: codex={sorted(actual_codex)}, claude={sorted(actual_claude)}"
        )

    for name, role in roles.items():
        access = role["access"]
        try:
            codex_binding = codex_bindings[access]
            claude_binding = claude_bindings[access]
        except KeyError as error:
            raise CanaryError(f"optional role {name} has no binding for access {access}") from error
        exact_keys(codex_binding, {"sandbox_mode", "web_search"}, f"Codex binding {access}")
        exact_keys(claude_binding, {"permissionMode", "tools"}, f"Claude binding {access}")

        codex_path = root / ".codex/agents" / f"{name}.toml"
        try:
            with codex_path.open("rb") as handle:
                codex_role = tomllib.load(handle)
        except (OSError, tomllib.TOMLDecodeError) as error:
            raise CanaryError(f"cannot parse {codex_path}: {error}") from error
        expected_codex_keys = {"name", "description", "sandbox_mode", "web_search", "developer_instructions"}
        exact_keys(codex_role, expected_codex_keys, f"generated Codex role {name}")
        if codex_role != {
            "name": name,
            "description": role["description"],
            "sandbox_mode": codex_binding["sandbox_mode"],
            "web_search": codex_binding["web_search"],
            "developer_instructions": role["instructions"],
        }:
            raise CanaryError(f"{codex_path} drifted from neutral role and runtime binding")

        claude_path = root / ".claude/agents" / f"{name}.md"
        claude_role, body = parse_claude_frontmatter(claude_path)
        expected_claude_keys = {"name", "description", "tools", "permissionMode"}
        exact_keys(claude_role, expected_claude_keys, f"generated Claude role {name}")
        if claude_role != {
            "name": name,
            "description": role["description"],
            "tools": ", ".join(claude_binding["tools"]),
            "permissionMode": claude_binding["permissionMode"],
        }:
            raise CanaryError(f"{claude_path} drifted from neutral role and runtime binding")
        if role["instructions"] not in body:
            raise CanaryError(f"{claude_path} omitted the neutral role instructions")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--contract",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "tests/runtime-compatibility.yaml",
    )
    parser.add_argument(
        "--project",
        type=Path,
        action="append",
        default=[],
        help="validate an onboarded project; repeat to validate multiple projects",
    )
    parser.add_argument(
        "--require-roles",
        action="store_true",
        help="require optional role output in every --project target",
    )
    args = parser.parse_args()
    try:
        repo = args.repo.resolve()
        versions = validate_cli_contract(load_yaml(args.contract.resolve()))
        project_roots = args.project or [repo / "template", repo / "templates/python", repo / "templates/rust"]
        for root in project_roots:
            root = root.resolve()
            validate_minimal_project(root, repo, allow_optional_roles=args.require_roles)
            if args.require_roles:
                validate_optional_roles(root, repo)
            print(f"PASS: {'optional role' if args.require_roles else 'minimal'} runtime contract {root}")
        print(f"PASS: offline CLI canary codex={versions['codex']} claude={versions['claude']}")
        print("INFO: remote model availability not checked (zero-network canary)")
        return 0
    except CanaryError as error:
        print(f"runtime-canary: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
