#!/usr/bin/env python3
"""Maintain lean project guidance. This tool stays in dev-template, not generated projects."""
from __future__ import annotations

import argparse
import base64
import binascii
import hashlib
import fnmatch
import json
import math
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import stat
import sys
import tempfile
import time
import tomllib

import yaml

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
from knowledge import validate_knowledge_registry

MARKER = "Generated by dev-template tools/template.py. Do not edit directly."
STATE = ".ai/template.json"
OVERLAYS = {"AI.md", "flake.nix", ".gitignore"}
SHARED = ("AGENTS.md", "CLAUDE.md", ".envrc", ".claude/settings.json",
          ".claude/hooks/statusline.sh", ".ai/context/.gitignore")
PROFILE_NAMES = ("roles", "skill:agent-context", "skill:frontend-design")
LOCAL_NAMES = {"local", "tmp", "sessions", "logs"}


class Error(ValueError):
    pass


def encode(data: bytes, mode: int = 0o644) -> dict:
    return {"kind": "file", "data": base64.b64encode(data).decode(), "mode": mode}


def file_asset(text: str, mode: int = 0o644) -> dict:
    return encode(text.encode(), mode)


def validate_asset(asset: dict | None):
    if asset is None:
        return
    if not isinstance(asset, dict):
        raise Error("backup asset must be a file, link, or null")
    if asset.get("kind") == "file":
        if set(asset) != {"kind", "data", "mode"} or not isinstance(asset["data"], str):
            raise Error("malformed file asset")
        if type(asset["mode"]) is not int or not 0 <= asset["mode"] <= 0o7777:
            raise Error("invalid file mode in backup")
        try:
            base64.b64decode(asset["data"], validate=True)
        except (ValueError, binascii.Error) as error:
            raise Error("invalid base64 in backup") from error
    elif asset.get("kind") == "link":
        if set(asset) != {"kind", "target"} or not isinstance(asset["target"], str) or not asset["target"] or "\0" in asset["target"]:
            raise Error("malformed link asset")
    else:
        raise Error("unknown backup asset kind")


def fingerprint(asset: dict | None) -> str | None:
    if asset is None:
        return None
    if asset["kind"] == "link":
        payload = b"link\0" + asset["target"].encode()
    else:
        payload = f"file:{asset['mode']:o}\0".encode() + base64.b64decode(asset["data"])
    return hashlib.sha256(payload).hexdigest()


def relative(name: str) -> PurePosixPath:
    path = PurePosixPath(name)
    if not name or path.is_absolute() or ".." in path.parts or path.as_posix() != name:
        raise Error(f"unsafe relative path: {name}")
    if path.parts[0] == ".git":
        raise Error("Git internals are never managed")
    return path


def is_local(name: str) -> bool:
    p = PurePosixPath(name)
    return (len(p.parts) > 1 and p.parts[0] in {".ai", ".codex", ".claude", ".agents"}
            and p.parts[1] in LOCAL_NAMES) or name == ".claude/settings.local.json"


def target(root: Path, name: str) -> Path:
    p = relative(name)
    current = root
    for part in p.parts[:-1]:
        current /= part
        if current.is_symlink():
            raise Error(f"refusing traversal through symlink: {current}")
        if current.exists() and not current.is_dir():
            raise Error(f"expected directory: {current}")
    return root / p


def read_asset(path: Path) -> dict | None:
    if path.is_symlink():
        return {"kind": "link", "target": os.readlink(path)}
    if not path.exists():
        return None
    if not path.is_file():
        raise Error(f"expected file or symlink: {path}")
    return encode(path.read_bytes(), stat.S_IMODE(path.stat().st_mode))


def source_asset(path: Path) -> dict | None:
    asset = read_asset(path)
    if asset and asset["kind"] == "file":
        asset["mode"] = 0o755 if asset["mode"] & 0o111 else 0o644
    return asset


def paths_under(directory: Path, local_root: Path | None = None):
    if not directory.exists() or directory.is_symlink():
        return
    for parent, directories, files in os.walk(directory, followlinks=False):
        if local_root is not None:
            directories[:] = [name for name in directories if not is_local((Path(parent) / name).relative_to(local_root).as_posix())]
        for name in list(directories):
            p = Path(parent) / name
            if p.is_symlink():
                directories.remove(name)
                yield p
        for name in files:
            yield Path(parent) / name


def read_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise Error(f"cannot read JSON: {path}: {error}") from error
    if not isinstance(data, dict):
        raise Error(f"expected object: {path}")
    return data


def serialized(data: dict) -> dict:
    return file_asset(json.dumps(data, indent=2, sort_keys=True) + "\n")


def empty_state() -> dict:
    return {"version": 3, "files": {}, "profiles": [], "overrides": {}, "startup_budget": 900}


def owned_name(name: str) -> bool:
    relative(name)
    return name in SHARED or any(name.startswith(p) for p in (
        ".ai/skills/", ".agents/skills/", ".claude/skills/", ".codex/agents/", ".claude/agents/"))


def load_state(root: Path, required: bool = True) -> dict:
    p = target(root, STATE)
    if p.is_symlink():
        raise Error("template state must be a regular file")
    if not p.exists():
        if required:
            raise Error("no v3 state; run onboard, or migrate for a legacy project")
        return empty_state()
    state = read_json(p)
    if set(state) != {"version", "files", "profiles", "overrides", "startup_budget"} or state["version"] != 3:
        raise Error("unsupported or malformed template state")
    if not isinstance(state["files"], dict) or not isinstance(state["profiles"], list):
        raise Error("invalid ownership state")
    if any(p not in PROFILE_NAMES for p in state["profiles"]) or len(set(state["profiles"])) != len(state["profiles"]):
        raise Error("invalid enabled profiles")
    if type(state["startup_budget"]) is not int or not 100 <= state["startup_budget"] <= 10000:
        raise Error("startup_budget must be an integer from 100 to 10000")
    for name, record in state["files"].items():
        if not owned_name(name) or is_local(name) or not isinstance(record, dict):
            raise Error(f"invalid managed file: {name}")
        if set(record) != {"hash", "profile"} or not isinstance(record["hash"], str) or not re.fullmatch(r"[0-9a-f]{64}", record["hash"]):
            raise Error(f"invalid fingerprint: {name}")
        profile = record["profile"]
        if profile not in ("core", *state["profiles"]):
            raise Error(f"unselected owner: {name}")
        if profile == "core" and name not in SHARED:
            raise Error(f"invalid core ownership: {name}")
        if profile == "roles" and not re.fullmatch(r"\.(codex/agents/[a-z]+\.toml|claude/agents/[a-z]+\.md)", name):
            raise Error(f"invalid role ownership: {name}")
        if profile.startswith("skill:") and not any(name.startswith(p + profile[6:] + "/") or name == p + profile[6:]
            for p in (".ai/skills/", ".agents/skills/", ".claude/skills/")):
            raise Error(f"invalid skill ownership: {name}")
    validate_overrides(state["overrides"])
    return state


def write_asset(path: Path, asset: dict | None):
    if asset is None:
        if path.exists() or path.is_symlink():
            path.unlink()
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".dev-template-", dir=path.parent)
    try:
        if asset["kind"] == "link":
            os.close(descriptor)
            os.unlink(temporary)
            os.symlink(asset["target"], temporary)
        else:
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(base64.b64decode(asset["data"]))
                os.fchmod(stream.fileno(), asset["mode"])
        os.replace(temporary, path)
    finally:
        if os.path.lexists(temporary):
            os.unlink(temporary)


def transaction(root: Path, changes: dict, label: str) -> Path | None:
    before = {}
    for name, asset in changes.items():
        validate_asset(asset)
        if is_local(name):
            raise Error(f"local state cannot be managed: {name}")
        before[name] = read_asset(target(root, name))
        validate_asset(before[name])
    changes = {name: asset for name, asset in changes.items() if asset != before[name]}
    if not changes:
        print(f"{label}: up to date")
        return None
    backup_dir = target(root, f".ai/local/dev-template/backups/{time.time_ns()}")
    backup_dir.mkdir(mode=0o700, parents=True)
    os.chmod(backup_dir, 0o700)
    write_asset(backup_dir / ".gitignore", file_asset("*\n", 0o600))
    record = {"version": 1, "operation": label,
              "before": {name: before[name] for name in changes}, "after": changes}
    backup = backup_dir / "backup.json"
    write_asset(backup, {**serialized(record), "mode": 0o600})
    applied = []
    try:
        # Remove symlinks first, so a reset can replace their former destinations safely.
        order = sorted(changes, key=lambda n: (changes[n] is not None, n.count("/"), n))
        for name in order:
            path = target(root, name)
            if read_asset(path) != before[name]:
                raise Error(f"file changed during preflight: {name}")
            applied.append(name)
            write_asset(path, changes[name])
    except BaseException:
        for name in reversed(applied):
            write_asset(target(root, name), before[name])
        raise
    # Prune empty directories after the successful transaction; never touch local state.
    for name in changes:
        p = (root / name).parent
        while p != root and not is_local(p.relative_to(root).as_posix()):
            if p == root / ".ai/skills" and any(
                (root / runtime / "skills").is_symlink()
                and os.readlink(root / runtime / "skills") == "../.ai/skills"
                for runtime in (".agents", ".claude", ".codex")
            ):
                break
            try:
                p.rmdir()
            except OSError:
                break
            p = p.parent
    print(f"{label}: changed {len(changes)} files; backup: {backup}")
    return backup


def core_assets(repo: Path) -> dict:
    guidance = (repo / "maintainer/guidance.md").read_text().strip()
    assets = {name: source_asset(repo / "template" / name) for name in SHARED if name not in {"AGENTS.md", "CLAUDE.md"}}
    for runtime, name in (("Codex", "AGENTS.md"), ("Claude Code", "CLAUDE.md")):
        assets[name] = file_asset(f"# {runtime}\n\n<!-- {MARKER} -->\n\n{guidance}\n")
    if any(asset is None for asset in assets.values()):
        raise Error("maintainer template assets are missing")
    return assets


def validate_overrides(overrides: dict):
    if not isinstance(overrides, dict) or set(overrides) - {"codex", "claude"}:
        raise Error("overrides must map codex/claude to role settings")
    for runtime, roles in overrides.items():
        if not isinstance(roles, dict) or set(roles) - {"scout", "researcher", "worker", "reviewer"}:
            raise Error("override names must be known roles")
        for settings in roles.values():
            allowed = {"model", "model_reasoning_effort"} if runtime == "codex" else {"model"}
            if not isinstance(settings, dict) or set(settings) - allowed or any(not isinstance(v, str) or not v.strip() for v in settings.values()):
                raise Error("overrides accept only nonempty model/effort strings")
            if "model_reasoning_effort" in settings and settings["model_reasoning_effort"] not in {"minimal", "low", "medium", "high", "xhigh"}:
                raise Error("unsupported Codex reasoning effort")


def profile_assets(repo: Path, profile: str, root: Path, overrides: dict) -> dict:
    if profile not in PROFILE_NAMES:
        raise Error(f"unknown profile: {profile}")
    if profile == "roles":
        roles = yaml.safe_load((repo / "optional/roles.yaml").read_text())["roles"]
        bindings = read_json(repo / "optional/runtime-bindings.json")
        assets = {}
        for name, role in roles.items():
            prompt = role["instructions"]
            codex = {"name": name, "description": role["description"], **bindings["codex"][role["access"]],
                     **overrides.get("codex", {}).get(name, {}), "developer_instructions": prompt}
            text = f"# {MARKER}\n" + "".join(f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in codex.items())
            assets[f".codex/agents/{name}.toml"] = file_asset(text)
            claude = {"name": name, "description": role["description"], **bindings["claude"][role["access"]],
                      **overrides.get("claude", {}).get(name, {})}
            claude["tools"] = ", ".join(claude["tools"])
            text = "---\n" + yaml.safe_dump(claude, sort_keys=False) + f"---\n\n<!-- {MARKER} -->\n\n{prompt}\n"
            assets[f".claude/agents/{name}.md"] = file_asset(text)
        return assets
    name = profile[6:]
    source = repo / "optional/skills" / name
    manifest = yaml.safe_load((source / "manifest.yaml").read_text())
    assets = {f".ai/skills/{name}/{p.relative_to(source).as_posix()}": source_asset(p) for p in paths_under(source)
              if any(fnmatch.fnmatch(p.relative_to(source).as_posix(), pattern) for pattern in manifest["package"])}
    if not assets:
        raise Error(f"skill source missing: {name}")
    for runtime in (".agents", ".claude"):
        view = target(root, f"{runtime}/skills")
        if view.is_symlink():
            if os.readlink(view) != "../.ai/skills":
                raise Error(f"custom skill discovery link: {view}")
        else:
            assets[f"{runtime}/skills/{name}"] = {"kind": "link", "target": f"../../.ai/skills/{name}"}
    return assets


def legacy_guard(root: Path):
    if (root / ".ai/project.yaml").exists() or (root / ".ai/project.yaml").is_symlink():
        raise Error("legacy project detected; ordinary sync does not upgrade it. Use migrate (v2), or migrate-v2 first (v1).")


def merge_assets(root: Path, state: dict, assets: dict, owner: str, changes: dict, strict: bool = False):
    for name, asset in assets.items():
        current = read_asset(target(root, name))
        known = state["files"].get(name)
        if current is not None and current != asset and (not known or fingerprint(current) != known["hash"]):
            if strict:
                raise Error(f"customized collision; preserved: {name}")
            print(f"preserved customized file: {name}")
            continue
        changes[name] = asset
        state["files"][name] = {"hash": fingerprint(asset), "profile": owner}


def sync(repo: Path, root: Path, onboard: bool = False):
    legacy_guard(root)
    if not any((root / p).exists() for p in (".git", "flake.nix", "Cargo.toml", "pyproject.toml", "package.json", "go.mod")):
        raise Error("run from a project root with .git, flake.nix, or a language manifest")
    state = load_state(root, required=not onboard)
    changes = {}
    merge_assets(root, state, core_assets(repo), "core", changes)
    for profile in state["profiles"]:
        merge_assets(root, state, profile_assets(repo, profile, root, state["overrides"]), profile, changes)
    if onboard and read_asset(target(root, "AI.md")) is None:
        changes["AI.md"] = source_asset(repo / "template/AI.md")
    changes[STATE] = serialized(state)
    transaction(root, changes, "onboard" if onboard else "sync")


def profile_command(repo: Path, root: Path, action: str, name: str | None, override_path: Path | None):
    if action == "list":
        for p in PROFILE_NAMES:
            print(p)
        return
    legacy_guard(root)
    state = load_state(root)
    if name not in PROFILE_NAMES:
        raise Error("select a profile from agent-profile list")
    if override_path and (name != "roles" or action != "enable"):
        raise Error("--overrides is available when enabling roles")
    changes = {}
    if action == "enable":
        if override_path:
            state["overrides"] = read_json(override_path)
            validate_overrides(state["overrides"])
        merge_assets(root, state, profile_assets(repo, name, root, state["overrides"]), name, changes, strict=True)
        state["profiles"] = sorted(set([*state["profiles"], name]))
    else:
        if name.startswith("skill:"):
            for p in paths_under(root / ".ai/skills" / name[6:]):
                path = p.relative_to(root).as_posix()
                if path not in state["files"]:
                    raise Error(f"unmanaged skill file; disable refused: {path}")
        for path, record in list(state["files"].items()):
            if record["profile"] == name:
                current = read_asset(target(root, path))
                if current is not None and fingerprint(current) != record["hash"]:
                    raise Error(f"customized profile file; disable refused: {path}")
                changes[path] = None
                del state["files"][path]
        state["profiles"] = [p for p in state["profiles"] if p != name]
        if name == "roles":
            state["overrides"] = {}
    changes[STATE] = serialized(state)
    transaction(root, changes, f"profile {action} {name}")


def migration_plan(repo: Path, root: Path) -> dict:
    if (root / STATE).exists():
        raise Error("already on v3; use sync")
    old_path = target(root, ".ai/project.yaml")
    if old_path.is_symlink():
        raise Error("custom project specification symlink; migration refused")
    old = yaml.safe_load(old_path.read_text())
    registry = read_json(repo / "migrations/v2-to-v3.json")
    if not isinstance(old, dict) or old.get("version") != 2:
        raise Error("migrate requires v2; use migrate-v2 for v1 first")
    def contract(data):
        return {k: v for k, v in data.items() if k not in {"project", "budgets"}}
    if not any(contract(old) == contract(yaml.safe_load(text)) for text in registry["project_specs"]):
        raise Error("custom project contract; reconcile it before migration")
    all_files = {p.relative_to(root).as_posix(): read_asset(p) for p in paths_under(root / ".ai")
                 if not is_local(p.relative_to(root).as_posix())}
    core = (".ai/agents/", ".ai/capabilities/", ".ai/generators/", ".ai/evals/")
    core_files = {".ai/instructions.md", ".ai/methodology.md", ".ai/policy.yaml"}
    known = lambda name, asset: fingerprint(asset) in registry["files"].get(name, [])
    changes = {".ai/project.yaml": None}
    for name, asset in all_files.items():
        if name in core_files or name.startswith(core):
            generated_cache = "__pycache__" in PurePosixPath(name).parts and name.endswith(".pyc") and asset["kind"] == "file"
            if not known(name, asset) and not generated_cache:
                raise Error(f"custom core file; migration refused: {name}")
            changes[name] = None
    # A customized skill is preserved as a complete unit, including extra references.
    prefix = ".ai/skills/agent-context/"
    skill_files = {n: a for n, a in all_files.items() if n.startswith(prefix)}
    if skill_files and all(known(n, a) for n, a in skill_files.items()):
        changes.update({n: None for n in skill_files})
    # Retire a dormant unchanged catalog only as a complete unit. Custom content
    # and activations may depend on other catalog units, so retain them together.
    catalog = {n: a for n, a in all_files.items() if n.startswith(".ai/catalog/")}
    units = {n.split("/")[2] for n in catalog if len(n.split("/")) > 3}
    complete = all(
        {n for n in catalog if n.startswith(f".ai/catalog/{unit}/")}
        == {n for n in registry["files"] if n.startswith(f".ai/catalog/{unit}/")}
        for unit in units
    )
    runtime_assets = {}
    for runtime in (".agents", ".claude", ".codex"):
        runtime_assets.update({p.relative_to(root).as_posix(): read_asset(p) for p in paths_under(root / runtime)
                               if not is_local(p.relative_to(root).as_posix())})
    referenced = any((root / runtime).is_symlink() for runtime in (".agents", ".claude", ".codex"))
    catalog_root = root / ".ai/catalog"
    for name, asset in {**all_files, **runtime_assets}.items():
        if asset["kind"] == "link":
            destination = (root / name).parent / asset["target"]
            if destination.resolve().is_relative_to(catalog_root.resolve()):
                referenced = True
    tool_assets = {n: a for n, a in all_files.items() if n.startswith(".ai/tools/")}
    unchanged_tools = all(known(n, a) for n, a in tool_assets.items())
    retire_catalog = (not catalog_root.is_symlink() and not (root / ".ai/tools").is_symlink()
                      and not referenced and complete and unchanged_tools and all(known(n, a) for n, a in catalog.items()))
    if retire_catalog:
        changes.update({n: None for n in catalog})
        name = ".ai/tools/skillctl.py"
        if name in all_files and known(name, all_files[name]):
            changes[name] = None
    preserved_skills = [n for n in all_files if n.startswith(".ai/skills/") and n not in changes]
    state = empty_state()
    budget = old.get("budgets", {}).get("always_loaded_tokens", 900)
    if type(budget) is int and 100 <= budget <= 10000:
        state["startup_budget"] = budget
    assets = core_assets(repo)
    for runtime in (".codex", ".claude", ".agents"):
        for p in paths_under(root / runtime):
            name = p.relative_to(root).as_posix()
            if is_local(name):
                continue
            asset = read_asset(p)
            if known(name, asset) and name not in assets:
                if name.endswith("/skills") and (preserved_skills or (root / ".ai/skills").is_symlink()):
                    continue
                changes[name] = None
    for name in ("CODEX.md", ".mcp.json"):
        asset = read_asset(target(root, name))
        if asset and known(name, asset):
            changes[name] = None
    for name, asset in assets.items():
        current = read_asset(target(root, name))
        if current is None or current == asset or known(name, current):
            changes[name] = asset
            state["files"][name] = {"hash": fingerprint(asset), "profile": "core"}
        else:
            # Old adapters may explicitly require removed files. Preserve their sources as well.
            if name in {"AGENTS.md", "CLAUDE.md"}:
                raise Error(f"custom adapter; migration refused: {name}")
            print(f"preserved customized file: {name}")
    legacy_copy = ".ai/context/legacy-project.yaml"
    current = read_asset(target(root, legacy_copy))
    if current is not None and current != read_asset(old_path):
        raise Error(f"legacy project record already customized: {legacy_copy}")
    changes[legacy_copy] = read_asset(old_path)
    changes[STATE] = serialized(state)
    return changes


def migrate(repo: Path, root: Path, apply: bool):
    changes = migration_plan(repo, root)
    print("v2 -> v3: preserve AI.md, project facts, context, custom/active workflows, and local state")
    for name in sorted(changes):
        print(f"  {'remove' if changes[name] is None else 'write '} {name}")
    if apply:
        transaction(root, changes, "migrate")
    else:
        print("Dry run; use --apply to migrate with a recoverable backup.")


def restore(root: Path, backup: Path):
    resolved = backup.resolve()
    backup_root = (root / ".ai/local/dev-template/backups").resolve()
    if not resolved.is_relative_to(backup_root):
        raise Error("backup must belong to this project's dev-template backups")
    record = read_json(resolved)
    if record.get("version") != 1 or not isinstance(record.get("before"), dict) or not isinstance(record.get("after"), dict) or set(record["before"]) != set(record["after"]):
        raise Error("malformed backup")
    for name in record["before"]:
        if not (name in {*SHARED, "AI.md", "flake.nix", "flake.lock", "CODEX.md", ".mcp.json"}
                or name.startswith((".ai/", ".agents/", ".claude/", ".codex/"))):
            raise Error(f"backup contains a non-agent file: {name}")
        validate_asset(record["before"][name])
        validate_asset(record["after"][name])
    for name, asset in record["after"].items():
        if is_local(name):
            raise Error("backup cannot overwrite local state")
        if read_asset(target(root, name)) != asset:
            raise Error(f"changed since backup; restore refused: {name}")
    transaction(root, record["before"], "restore")


def reset(repo: Path, root: Path, yes: bool, flavor: str | None):
    if not any((root / p).exists() for p in (".git", "flake.nix", "Cargo.toml", "pyproject.toml", "package.json", "go.mod")):
        raise Error("reset requires a project root")
    if flavor is None:
        flake = (root / "flake.nix").read_text() if (root / "flake.nix").is_file() else ""
        flavor = "rust" if (root / "Cargo.toml").exists() or "rust-overlay" in flake else "python" if (root / "pyproject.toml").exists() or "pkgs.uv" in flake else "default"
    print(f"Reset agent guidance, AI.md, .envrc, and flake using {flavor}; preserve source code and local runtime state.")
    if not yes and input("Type reset to continue: ").strip() != "reset":
        raise Error("reset cancelled")
    source = repo / ("template" if flavor == "default" else f"templates/{flavor}")
    changes = {}
    for directory in (".ai", ".codex", ".claude", ".agents"):
        path = root / directory
        if path.is_symlink():
            raise Error(f"custom runtime directory symlink: {directory}")
        for p in paths_under(path):
            name = p.relative_to(root).as_posix()
            if not is_local(name):
                changes[name] = None
    for name in ("AI.md", "AGENTS.md", "CLAUDE.md", "CODEX.md", ".mcp.json", "flake.lock"):
        if read_asset(target(root, name)) is not None:
            changes[name] = None
    for p in paths_under(source):
        name = p.relative_to(source).as_posix()
        if not is_local(name) and name != ".gitignore":
            changes[name] = source_asset(p)
    transaction(root, changes, "reset")


def token_estimate(text: str) -> int:
    return math.ceil(max(len(text.encode("utf-8")) / 4, len(text.split()) * 1.3))


def stats(root: Path) -> dict:
    guidance = token_estimate((root / "AI.md").read_text()) if (root / "AI.md").is_file() else 0
    adapter = max((token_estimate((root / p).read_text()) for p in ("AGENTS.md", "CLAUDE.md") if (root / p).is_file()), default=0)
    roles = []
    for runtime, pattern in ((".codex", "*.toml"), (".claude", "*.md")):
        cost = 0
        for path in (root / runtime / "agents").glob(pattern):
            if runtime == ".codex":
                data = tomllib.loads(path.read_text())
            else:
                text = path.read_text()
                data = yaml.safe_load(text.split("---", 2)[1]) if text.startswith("---\n") else {}
            cost += token_estimate(str(data.get("name", path.stem)) + " " + str(data.get("description", "")))
        roles.append(cost)
    skills = []
    for view in (".agents/skills", ".claude/skills"):
        cost = 0
        seen = set()
        for path in (root / view).glob("*/SKILL.md"):
            resolved = path.resolve()
            if resolved in seen:
                continue
            seen.add(resolved)
            text = path.read_text()
            data = yaml.safe_load(text.split("---", 2)[1]) if text.startswith("---\n") else {}
            cost += token_estimate(str(data.get("name", path.parent.name)) + " " + str(data.get("description", "")))
        skills.append(cost)
    result = {"guidance_tokens": guidance + adapter, "role_descriptions_tokens": max(roles, default=0),
              "skill_descriptions_tokens": max(skills, default=0)}
    result["startup_tokens"] = sum(result.values())
    # Count the agent/template footprint without walking application builds or Git.
    files = {root / n for n in (OVERLAYS | set(SHARED) | {STATE, "CODEX.md", ".mcp.json"})}
    for runtime in (".ai", ".agents", ".claude", ".codex"):
        files.update(p for p in paths_under(root / runtime, local_root=root)
                     if not is_local(p.relative_to(root).as_posix()))
    result["regular_files"] = sum(p.is_file() and not p.is_symlink() for p in files)
    return result


def doctor(repo: Path, root: Path) -> list[str]:
    legacy_guard(root)
    state = load_state(root)
    issues = []
    expected = core_assets(repo)
    for p in state["profiles"]:
        expected.update(profile_assets(repo, p, root, state["overrides"]))
    for name, asset in expected.items():
        actual = read_asset(target(root, name))
        if actual is None:
            issues.append(f"missing: {name}")
        elif name in state["files"] and fingerprint(actual) != state["files"][name]["hash"]:
            issues.append(f"customized: {name}")
        elif name in state["files"] and actual != asset:
            issues.append(f"outdated; run sync: {name}")
        elif name not in state["files"]:
            print(f"preserved unmanaged file: {name}")
    for runtime in (".agents", ".claude", ".codex"):
        view = root / runtime / "skills"
        if view.is_symlink() and not view.exists():
            issues.append(f"broken skill link: {view.relative_to(root)}")
        for path in view.glob("*"):
            if path.is_symlink() and not path.exists():
                issues.append(f"broken skill link: {path.relative_to(root)}")
    if not (root / "AI.md").is_file():
        issues.append("missing: AI.md")
    settings = root / ".claude/settings.json"
    if settings.is_file():
        read_json(settings)
    config = root / ".codex/config.toml"
    if config.is_file():
        tomllib.loads(config.read_text())
    registry = ".ai/context/knowledge-sources.yaml"
    target(root, registry)
    try:
        validate_knowledge_registry(root, registry)
    except ValueError as error:
        raise Error(str(error)) from error
    costs = stats(root)
    if costs["startup_tokens"] > state["startup_budget"]:
        issues.append(f"startup budget exceeded: {costs['startup_tokens']} > {state['startup_budget']}")
    for issue in issues:
        print(f"warning: {issue}")
    print(f"doctor: {len(issues)} warnings; estimated startup {costs['startup_tokens']} tokens")
    return issues


def generate(repo: Path):
    assets = core_assets(repo)
    state = empty_state()
    state["files"] = {n: {"hash": fingerprint(a), "profile": "core"} for n, a in assets.items()}
    assets[STATE] = serialized(state)
    for root in (repo / "template", repo / "templates/python", repo / "templates/rust"):
        for name, asset in assets.items():
            p = target(root, name)
            if read_asset(p) != asset:
                write_asset(p, asset)
    # This repository explicitly selects the maintainer skill; user projects do not.
    sync(repo, repo)
    print("generated base, language adapters, and maintainer guidance")


def check(repo: Path):
    expected = core_assets(repo)
    state = empty_state()
    state["files"] = {n: {"hash": fingerprint(a), "profile": "core"} for n, a in expected.items()}
    expected[STATE] = serialized(state)
    for root in (repo / "template", repo / "templates/python", repo / "templates/rust"):
        actual_names = {p.relative_to(root).as_posix() for p in paths_under(root) if not is_local(p.relative_to(root).as_posix())}
        if actual_names != set(expected) | OVERLAYS:
            raise Error(f"unexpected template files: {root}: {sorted(actual_names ^ (set(expected) | OVERLAYS))}")
        for name, asset in expected.items():
            if read_asset(target(root, name)) != asset:
                raise Error(f"generated file drift: {root / name}")
        if doctor(repo, root):
            raise Error(f"template contract failed: {root}")
    if doctor(repo, repo):
        raise Error("maintainer contract failed")
    print("v3 contracts: zero default skills, roles, model pins, and project compilers")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("generate", "check", "stats", "onboard", "sync", "doctor", "reset", "migrate", "profile", "restore"):
        p = sub.add_parser(name)
        p.add_argument("--root", type=Path, default=Path.cwd())
        if name == "reset":
            p.add_argument("--yes", action="store_true")
            p.add_argument("--flavor", choices=("default", "rust", "python"))
        if name == "migrate":
            p.add_argument("--apply", action="store_true")
        if name == "profile":
            p.add_argument("action", choices=("list", "enable", "disable"))
            p.add_argument("name", nargs="?")
            p.add_argument("--overrides", type=Path)
        if name == "restore":
            p.add_argument("backup", type=Path)
    args = parser.parse_args()
    repo, root = args.repo.resolve(), args.root.resolve()
    try:
        if args.command == "generate":
            generate(repo)
        elif args.command == "check":
            check(repo)
        elif args.command == "stats":
            print(json.dumps(stats(root), indent=2))
        elif args.command in {"onboard", "sync"}:
            sync(repo, root, onboard=args.command == "onboard")
        elif args.command == "doctor":
            return 1 if doctor(repo, root) else 0
        elif args.command == "reset":
            reset(repo, root, args.yes, args.flavor)
        elif args.command == "migrate":
            migrate(repo, root, args.apply)
        elif args.command == "profile":
            profile_command(repo, root, args.action, args.name, args.overrides)
        elif args.command == "restore":
            restore(root, args.backup)
    except (Error, OSError, UnicodeError, yaml.YAMLError, tomllib.TOMLDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
